### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ghost** [shbones/More-Mountains#1]
Idk how else to get a message to you so im using this.

I have wanted a mod like this for so long and im exited to see where it goes, its always kinda anoyed me that TP bosses are kinda a joke and dont even offer a real challnge to experienced players an idea ive always had was for mountain shrines to make bosses harder by giving them stat multiplyers/armor or maybe items to use depending on the boss instead of just adding more bosses. Because once you can one-shot bosses the shrines just become free items, so stoping the insta death and making the bosses into an actual fight that adds real "RISK" to the game so players stop and think about the risk and if its worth it would be a game changer.

**Comment by shbones** [comment]
Thanks for the comment! I should have included my discord handle in the Readme--I'll update that with the next update. Are you in the Risk of Rain 2 Modding discord (https://discord.gg/nkza4afY) ? My discord handle is shbones#0085, and there is probably the best place to discuss or reach me.
